package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_property_notify_event_t extends Structure {
	public byte response_type;
	public byte pad0;
	public short sequence;
	/** C type : xcb_window_t */
	public int window;
	/** C type : xcb_atom_t */
	public int atom;
	/** C type : xcb_timestamp_t */
	public int time;
	public byte state;
	/** C type : uint8_t[3] */
	public byte[] pad1 = new byte[3];
	public xcb_property_notify_event_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("response_type", "pad0", "sequence", "window", "atom", "time", "state", "pad1");
	}
	/**
	 * @param window C type : xcb_window_t<br>
	 * @param atom C type : xcb_atom_t<br>
	 * @param time C type : xcb_timestamp_t<br>
	 * @param pad1 C type : uint8_t[3]
	 */
	public xcb_property_notify_event_t(byte response_type, byte pad0, short sequence, int window, int atom, int time, byte state, byte pad1[]) {
		super();
		this.response_type = response_type;
		this.pad0 = pad0;
		this.sequence = sequence;
		this.window = window;
		this.atom = atom;
		this.time = time;
		this.state = state;
		if ((pad1.length != this.pad1.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad1 = pad1;
	}
	public xcb_property_notify_event_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_property_notify_event_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_property_notify_event_t implements Structure.ByValue {
		
	};
}
