package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_change_keyboard_control_value_list_t extends Structure {
	public int key_click_percent;
	public int bell_percent;
	public int bell_pitch;
	public int bell_duration;
	public int led;
	public int led_mode;
	/** C type : xcb_keycode32_t */
	public int key;
	public int auto_repeat_mode;
	public xcb_change_keyboard_control_value_list_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("key_click_percent", "bell_percent", "bell_pitch", "bell_duration", "led", "led_mode", "key", "auto_repeat_mode");
	}
	/** @param key C type : xcb_keycode32_t */
	public xcb_change_keyboard_control_value_list_t(int key_click_percent, int bell_percent, int bell_pitch, int bell_duration, int led, int led_mode, int key, int auto_repeat_mode) {
		super();
		this.key_click_percent = key_click_percent;
		this.bell_percent = bell_percent;
		this.bell_pitch = bell_pitch;
		this.bell_duration = bell_duration;
		this.led = led;
		this.led_mode = led_mode;
		this.key = key;
		this.auto_repeat_mode = auto_repeat_mode;
	}
	public xcb_change_keyboard_control_value_list_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_change_keyboard_control_value_list_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_change_keyboard_control_value_list_t implements Structure.ByValue {
		
	};
}
