package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_configure_window_value_list_t extends Structure {
	public int x;
	public int y;
	public int width;
	public int height;
	public int border_width;
	/** C type : xcb_window_t */
	public int sibling;
	public int stack_mode;
	public xcb_configure_window_value_list_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("x", "y", "width", "height", "border_width", "sibling", "stack_mode");
	}
	/** @param sibling C type : xcb_window_t */
	public xcb_configure_window_value_list_t(int x, int y, int width, int height, int border_width, int sibling, int stack_mode) {
		super();
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		this.border_width = border_width;
		this.sibling = sibling;
		this.stack_mode = stack_mode;
	}
	public xcb_configure_window_value_list_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_configure_window_value_list_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_configure_window_value_list_t implements Structure.ByValue {
		
	};
}
