package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_change_window_attributes_value_list_t extends Structure {
	/** C type : xcb_pixmap_t */
	public int background_pixmap;
	public int background_pixel;
	/** C type : xcb_pixmap_t */
	public int border_pixmap;
	public int border_pixel;
	public int bit_gravity;
	public int win_gravity;
	public int backing_store;
	public int backing_planes;
	public int backing_pixel;
	/** C type : xcb_bool32_t */
	public int override_redirect;
	/** C type : xcb_bool32_t */
	public int save_under;
	public int event_mask;
	public int do_not_propogate_mask;
	/** C type : xcb_colormap_t */
	public int colormap;
	/** C type : xcb_cursor_t */
	public int cursor;
	public xcb_change_window_attributes_value_list_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("background_pixmap", "background_pixel", "border_pixmap", "border_pixel", "bit_gravity", "win_gravity", "backing_store", "backing_planes", "backing_pixel", "override_redirect", "save_under", "event_mask", "do_not_propogate_mask", "colormap", "cursor");
	}
	public xcb_change_window_attributes_value_list_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_change_window_attributes_value_list_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_change_window_attributes_value_list_t implements Structure.ByValue {
		
	};
}
