package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_change_keyboard_mapping_request_t extends Structure {
	public byte major_opcode;
	public byte keycode_count;
	public short length;
	/** C type : xcb_keycode_t */
	public byte first_keycode;
	public byte keysyms_per_keycode;
	/** C type : uint8_t[2] */
	public byte[] pad0 = new byte[2];
	public xcb_change_keyboard_mapping_request_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("major_opcode", "keycode_count", "length", "first_keycode", "keysyms_per_keycode", "pad0");
	}
	/**
	 * @param first_keycode C type : xcb_keycode_t<br>
	 * @param pad0 C type : uint8_t[2]
	 */
	public xcb_change_keyboard_mapping_request_t(byte major_opcode, byte keycode_count, short length, byte first_keycode, byte keysyms_per_keycode, byte pad0[]) {
		super();
		this.major_opcode = major_opcode;
		this.keycode_count = keycode_count;
		this.length = length;
		this.first_keycode = first_keycode;
		this.keysyms_per_keycode = keysyms_per_keycode;
		if ((pad0.length != this.pad0.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pad0 = pad0;
	}
	public xcb_change_keyboard_mapping_request_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_change_keyboard_mapping_request_t implements Structure.ByReference {
		
	};
	public static class ByValue extends xcb_change_keyboard_mapping_request_t implements Structure.ByValue {
		
	};
}
