package com.yi.ylwm.xcb;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /usr/include/xcb/xproto.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xcb_change_gc_value_list_t extends Structure {
	public int function;
	public int plane_mask;
	public int foreground;
	public int background;
	public int line_width;
	public int line_style;
	public int cap_style;
	public int join_style;
	public int fill_style;
	public int fill_rule;
	/** C type : xcb_pixmap_t */
	public int tile;
	/** C type : xcb_pixmap_t */
	public int stipple;
	public int tile_stipple_x_origin;
	public int tile_stipple_y_origin;
	/** C type : xcb_font_t */
	public int font;
	public int subwindow_mode;
	/** C type : xcb_bool32_t */
	public int graphics_exposures;
	public int clip_x_origin;
	public int clip_y_origin;
	/** C type : xcb_pixmap_t */
	public int clip_mask;
	public int dash_offset;
	public int dashes;
	public int arc_mode;
	public xcb_change_gc_value_list_t() {
		super();
	}
	@Override
protected List<String> getFieldOrder(){
		return Arrays.asList("function", "plane_mask", "foreground", "background", "line_width", "line_style", "cap_style", "join_style", "fill_style", "fill_rule", "tile", "stipple", "tile_stipple_x_origin", "tile_stipple_y_origin", "font", "subwindow_mode", "graphics_exposures", "clip_x_origin", "clip_y_origin", "clip_mask", "dash_offset", "dashes", "arc_mode");
	}
	public xcb_change_gc_value_list_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xcb_change_gc_value_list_t implements Structure.ByReference {

	};
	public static class ByValue extends xcb_change_gc_value_list_t implements Structure.ByValue {

	};
}
